/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CVController__factory } from "./CVController__factory";
export { EmployeeCVController__factory } from "./EmployeeCVController__factory";
